#define ENABLE_LOGGING 1
#define ENABLE_DISPLAY 1
#define ENABLE_BUTTON 1
#define ENABLE_BEEPER 1
#define ENABLE_AMBIENT 1
#define ENABLE_FILESYSTEM 1

// Components
#define TEST_FLAG 1
#define ENABLE_IMAGE 1
// #define ENABLE_ANIMATION 1
#define ENABLE_FSANIMATION 1
#define ENABLE_TEXT 1

// LOGGING SETTINGS
#define BAUD_RATE 115200
